windowrule = workspace 2, match:class firefox
windowrule = workspace 2, match:class kitty
windowrule = workspace 5, match:class google-chrome
windowrule = workspace 4, match:class jetbrains-idea
windowrule = workspace 3, match:class org.gnome.Evolution
windowrule = workspace 6, match:class org.gajim.Gajim
windowrule = workspace 6, match:class org.telegram.desktop
windowrule = workspace 6, match:class signal

windowrule = workspace 8, keep_aspect_ratio on, match:title Euro Truck Simulator 2
#windowrulev2 = float,title:Euro Truck Simulator 2
#windowrulev2 = fullscreen,title:Euro Truck Simulator 2
windowrule = float on, match:class org.gnome.Calculator

# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule = center on, no_focus on, border_size 0, match:class ^(jetbrains-.*)$, match:title ^(splash)$, match:float 1
# search dialog
windowrule = dim_around on, center on, match:class ^(jetbrains-.*)$, match:float 1, match:title ^(?!win)
# autocomplete & menus
windowrule = no_anim on, no_initial_focus on, rounding 0, match:class ^(jetbrains-.*)$, match:title ^(win.*)$


#! Center popups/find windows
windowrule = center on, stay_focused on, border_size 0, match:class ^(jetbrains-.*)$, match:title ^( )$, match:float 1
#! Disable window flicker when autocomplete or tooltips appear
windowrule = no_focus on, match:class ^(jetbrains-.*)$, match:title ^(win.*)$, match:float 1
